export const english = {
  brand: "Loctober",
  brandTag: "the board",
  athlete: "Athlete",
  you: "You",
  person: "{count} person",
  people: "{count} people",
  thisMonth: "{amount} this month",
  meta: {
    title: "Loctober",
    titleTemplate: "%s · Loctober",
    description:
      "A private scoreboard for a month-long lock-in. Daily volume, a running total, and one finale.",
  },
  mode: {
    enter: "Minion mode",
    exit: "Poopaye",
  },
  pending: {
    creating: "Creating…",
    saving: "Saving…",
    adding: "Adding…",
  },
  ordinal: {
    st: "st",
    nd: "nd",
    rd: "rd",
    th: "th",
  },
  kind: {
    daily: "Daily",
    finale: "Finale",
  },
  loading: {
    day: "Loading the day…",
    month: "Adding up the month…",
    finale: "Loading the finale…",
    crew: "Loading the crew…",
    invite: "Opening the invite…",
  },
  landing: {
    kicker: "October, locked in",
    hero: "A month on the board.",
    lede: "Loctober is a private scoreboard for the people you actually train with. Log the day, watch the month add up, and settle it with one finale.",
    start: "Start a board",
    signIn: "Sign in",
    yourBoards: "Your boards",
    today: "Today",
    todayBlurb: "Who showed up, and for how many.",
    month: "The month",
    monthBlurb: "Volume, stacked, with the days you missed left blank.",
    finale: "The last day",
    finaleBlurb: "One max effort. Or the whole presidential test.",
    sampleLabel: "Sample board",
    sampleMetric: "Push-ups",
    sampleNote:
      "Boards are invite-only. Send a link, they sign in with Google, and they can log. Strangers cannot.",
    sampleName1: "Sam",
    sampleName2: "Alex",
    sampleName3: "Jules",
  },
  home: {
    title: "Your boards",
    subtitle: "The challenges you own or were invited to.",
    new: "New",
    emptyTitle: "Nothing here yet.",
    emptyBody: "Start a board and send the link, or open an invite from a friend.",
    start: "Start a board",
    today: "Today",
    metricMonth: "{name} this month",
    noDaily: "No daily tracker yet.",
    privateBoard: "That board is private. Ask for an invite link.",
    badInvite: "That invite link doesn't match a board.",
  },
  missing: {
    title: "That page is not on the board.",
    body: "The link may be old, or the board may have been deleted.",
    home: "Back home",
  },
  tabs: {
    today: "Today",
    month: "Month",
    finale: "Finale",
    crew: "Crew",
  },
  header: {
    allBoards: "All boards",
  },
  today: {
    noMetricTitle: "No daily tracker yet.",
    noMetricBody: "Add one from the crew page.",
    previousDay: "Previous day",
    nextDay: "Next day",
    back: "Back to today",
    label: "Today",
    youRank: "You're {place} on this day.",
    youEmpty: "You haven't logged this day.",
    streak: "{count}-day streak.",
    clear: "Clear",
    heading: "The day",
    empty: "Nobody is on this board yet.",
    detailStreak: "{streak}-day streak · {total} this month",
    detailMonth: "{total} this month",
    log: "Log {name}",
    closeLog: "Close log",
    logTitle: "Log it",
    close: "Close",
    saveDay: "Save this day",
  },
  month: {
    needTracker: "Add a daily tracker from the crew page.",
    title: "Month volume",
    blurb:
      "Every logged day, added up. Ember is a day above zero. A muted square is a zero. Blank squares are days with no number.",
    logged: "{day} logged",
    notLogged: "{day} not logged",
    tipLogged: "{day}: {value}",
    tipEmpty: "{day}: not logged",
  },
  finale: {
    emptyTitle: "No finale yet.",
    emptyBody:
      "The owner can add one from the crew page. A max set of push-ups is the usual closer.",
    title: "Finale",
    blurb: "One score per event. You can update it until three days after the board ends.",
    closed: "The window for new scores is closed.",
    higher: "Higher wins",
    lower: "Lower wins",
    save: "Save score",
    empty: "No scores yet.",
  },
  crew: {
    welcome: "You're in. Send this.",
    invite: "Invite",
    linkTitle: "The link",
    linkBody:
      "Anyone with this link can sign in and join. Without it, they can't see the board.",
    rotate: "Rotate link",
    rotateHint: "The old link stops working.",
    title: "Crew",
    owner: "Owner",
    member: "Member",
    remove: "Remove",
    nickTitle: "Your name on the board",
    nickHint: "Nickname, or blank to use your account name.",
    nickSave: "Save nickname",
    boardName: "Board name",
    rename: "Rename",
    trackers: "Trackers",
    trackersBody:
      "Days use the {zone} calendar. Add steps, miles, pull-ups, or another finale event whenever you want.",
    addTitle: "Add a tracker",
    name: "Name",
    namePlaceholder: "Steps",
    unit: "Unit",
    unitPlaceholder: "steps",
    when: "When",
    everyDay: "Every day",
    finale: "Finale",
    number: "Number",
    whole: "Whole number",
    decimal: "Decimal",
    time: "Time",
    add: "Add tracker",
    delete: "Delete this board",
    leave: "Leave this board",
  },
  join: {
    invite: "Invite",
    already: "{count} already on it",
    open: "Open the board",
    join: "Join this board",
    signIn: "Sign in to join",
    account: "Make an account",
  },
  auth: {
    signInTitle: "Sign in",
    signInBody: "Google is the fast way in. Email works too, if that is what you have.",
    signInLoading: "Loading sign in…",
    signUpTitle: "Make an account",
    signUpBody: "You only need this once. An invite link drops you onto a board after.",
    signUpLoading: "Loading sign up…",
  },
  create: {
    title: "New board",
    blurb: "You can add steps, miles, or another finale event after this.",
    setting: "Setting the month…",
    cancel: "Cancel",
    name: "Board name",
    namePlaceholder: "October push-ups",
    starts: "Starts",
    ends: "Ends",
    timezone: "Timezone for “today”",
    tracking: "What are you tracking?",
    submit: "Create board",
  },
  score: {
    minutes: "Minutes",
    seconds: "Seconds",
    secondMark: "s",
    lowerWins: "Lower time wins. Saving replaces your finale score.",
    replacesFinale: "Saving replaces your finale score.",
    replacesDay: "This replaces the total for this day{unit}.",
    save: "Save",
  },
  invite: {
    preparing: "Preparing link…",
    label: "Invite link",
    copied: "Copied",
    copy: "Copy link",
  },
  templates: {
    pushups: {
      name: "Push-up month",
      blurb: "Log push-ups every day. On the last stretch, one max set.",
    },
    grind: {
      name: "The whole grind",
      blurb: "Push-ups, pull-ups, and miles, then a max set of push-ups.",
    },
    presidential: {
      name: "Presidential",
      blurb: "Daily push-ups, then the test: push-ups, sit-ups, pull-ups, and a mile.",
    },
  },
  tz: {
    pacific: "Pacific",
    mountain: "Mountain",
    arizona: "Arizona",
    central: "Central",
    eastern: "Eastern",
    hawaii: "Hawaii",
    london: "London",
    europe: "Central Europe",
    india: "India",
    tokyo: "Tokyo",
    sydney: "Sydney",
    utc: "UTC",
  },
  err: {
    check: "Check that and try again.",
    negative: "Use a number that isn't negative.",
    tooBig: "That number is too big to be a daily log.",
    time: "Keep the time under 24 hours.",
    nameShort: "Give the board a name.",
    nameLong: "Keep the name under 60 characters.",
    start: "Pick a start date.",
    end: "Pick an end date.",
    zone: "Pick a timezone from the list.",
    endBefore: "The end date has to be on or after the start.",
    span: "Keep a board to 45 days or fewer.",
    notOnBoard: "You are not on this board.",
    logMissing: "That log isn't on this board.",
    dayOutside: "That day is outside this board.",
    future: "You can't log a future day.",
    eventMissing: "That event isn't on this board.",
    finaleClosed: "The finale window for this board is closed.",
    renameLength: "Use a name between 2 and 60 characters.",
    renameOwner: "Only the person who made the board can rename it.",
    nickLength: "Keep the nickname under 24 characters.",
    trackerName: "Name the thing you're tracking.",
    trackerNameLong: "Keep the tracker name under 40 characters.",
    unitLong: "Keep the unit under 12 characters.",
    ownerOnly: "Only the owner can add a tracker.",
  },
  ok: {
    saved: "Saved.",
    finaleSaved: "Finale score saved.",
    nameUpdated: "Name updated.",
    nicknameSaved: "Nickname saved.",
    accountName: "Using your account name.",
    trackerAdded: "{name} is on the board.",
  },
} as const;

type DeepString<T> = {
  [K in keyof T]: T[K] extends string ? string : DeepString<T[K]>;
};

export type Copy = DeepString<typeof english>;

export const minion = {
  brand: "Bellober",
  brandTag: "da board",
  athlete: "Baboi",
  you: "Me",
  person: "{count} baboi",
  people: "{count} babois",
  thisMonth: "{amount} dis moon",
  meta: {
    title: "Bellober",
    titleTemplate: "%s · Bellober",
    description: "Secret banana board. Day day count, moon stack, one kaboom.",
  },
  mode: {
    enter: "Minion mode",
    exit: "Poopaye",
  },
  pending: {
    creating: "Papoy…",
    saving: "Tank yu…",
    adding: "Papoy…",
  },
  ordinal: {
    st: "-hana",
    nd: "-dul",
    rd: "-sae",
    th: "-po",
  },
  kind: {
    daily: "Day day",
    finale: "Kaboom",
  },
  loading: {
    day: "Luk da day…",
    month: "Count da banana…",
    finale: "Luk da kaboom…",
    crew: "Luk da boss…",
    invite: "Luk da link…",
  },
  landing: {
    kicker: "Bello, lock lock",
    hero: "Banana moon. Da board.",
    lede: "Bellober para tu babois. Log da day, banana da moon, kaboom da end. Tulaliloo!",
    start: "Papoy board",
    signIn: "Bello in",
    yourBoards: "Para tu boards",
    today: "Bello day",
    todayBlurb: "Who show up, and how many banana.",
    month: "Da moon",
    monthBlurb: "Banana stack stack. Empty day stay bi-do.",
    finale: "Da kaboom day",
    finaleBlurb: "One big push. Or da whole boss test.",
    sampleLabel: "Luk board",
    sampleMetric: "Pushy-po",
    sampleNote: "Board is secret. Send link, baboi bello with Google, then log. Strangers? No no no.",
    sampleName1: "Kevin",
    sampleName2: "Stuart",
    sampleName3: "Bob",
  },
  home: {
    title: "Para tu boards",
    subtitle: "Boards me own, or bello invite.",
    new: "Papoy",
    emptyTitle: "Bi-do. Empty.",
    emptyBody: "Papoy board and send da link, or open baboi invite.",
    start: "Papoy board",
    today: "Bello day",
    metricMonth: "{name} dis moon",
    noDaily: "Bi-do day tracker.",
    privateBoard: "Board is secret. Ask para bello link.",
    badInvite: "Link go bi-do. No board.",
  },
  missing: {
    title: "Page go bi-do.",
    body: "Link old, or board go kaboom.",
    home: "Poopaye home",
  },
  tabs: {
    today: "Bello",
    month: "Banana",
    finale: "Kaboom",
    crew: "Boss",
  },
  header: {
    allBoards: "All da boards",
  },
  today: {
    noMetricTitle: "Bi-do day tracker.",
    noMetricBody: "Papoy one from da boss page.",
    previousDay: "Luk back",
    nextDay: "Luk next",
    back: "Bello day",
    label: "Bello day",
    youRank: "Me {place} po ka dis day.",
    youEmpty: "Me bi-do dis day.",
    streak: "{count} banana streak.",
    clear: "Bi-do",
    heading: "Da day",
    empty: "Bi-do. No baboi on da board.",
    detailStreak: "{streak} banana streak · {total} dis moon",
    detailMonth: "{total} dis moon",
    log: "Luk {name}",
    closeLog: "Poopaye log",
    logTitle: "Luk it",
    close: "Poopaye",
    saveDay: "Tank yu day",
  },
  month: {
    needTracker: "Papoy day tracker from da boss page.",
    title: "Banana moon",
    blurb:
      "Every banana day, stack stack. Ember mean more than zero. Muted square mean zero. Empty square mean bi-do.",
    logged: "{day} banana",
    notLogged: "{day} bi-do",
    tipLogged: "{day}: {value}",
    tipEmpty: "{day}: bi-do",
  },
  finale: {
    emptyTitle: "Bi-do kaboom.",
    emptyBody: "Boss papoy one from da crew page. One big pushy is da closer. Tulaliloo.",
    title: "Kaboom",
    blurb: "One score, one kaboom. Me can swap until three days after da board poopaye.",
    closed: "Kaboom window poopaye. Bi-do.",
    higher: "Big number win",
    lower: "Small number win",
    save: "Tank yu score",
    empty: "Bi-do scores.",
  },
  crew: {
    welcome: "Bello! Send dis.",
    invite: "Bello link",
    linkTitle: "Da link",
    linkBody: "Baboi with dis link can bello and join. No link, no board. Bi-do.",
    rotate: "Spin da link",
    rotateHint: "Old link go poopaye.",
    title: "Boss crew",
    owner: "Boss",
    member: "Baboi",
    remove: "Poopaye",
    nickTitle: "Para tu name",
    nickHint: "Nickname, or empty para account name.",
    nickSave: "Tank yu name",
    boardName: "Da board name",
    rename: "Swap name",
    trackers: "Da counts",
    trackersBody:
      "Days go {zone} clock. Papoy steps, miles, pull-ups, or one more kaboom. Pwede na.",
    addTitle: "Papoy tracker",
    name: "Name",
    namePlaceholder: "Steppies",
    unit: "Bits",
    unitPlaceholder: "steppies",
    when: "When-when",
    everyDay: "Day day",
    finale: "Kaboom",
    number: "Count",
    whole: "Big count",
    decimal: "Little count",
    time: "Tick tock",
    add: "Papoy tracker",
    delete: "Kaboom dis board",
    leave: "Poopaye dis board",
  },
  join: {
    invite: "Bello link",
    already: "{count} already on it",
    open: "Luk da board",
    join: "Me join",
    signIn: "Bello in, me join",
    account: "Papoy account",
  },
  auth: {
    signInTitle: "Bello in",
    signInBody: "Google go fast. Email pwede na too.",
    signInLoading: "Luk da bello…",
    signUpTitle: "Papoy account",
    signUpBody: "One time only. Invite link drop me on da board. Bello.",
    signUpLoading: "Luk da papoy…",
  },
  create: {
    title: "Papoy board",
    blurb: "Papoy steps, miles, or one more kaboom after dis.",
    setting: "Count da moon…",
    cancel: "Poopaye",
    name: "Da name",
    namePlaceholder: "Banana pushy",
    starts: "Go go",
    ends: "Poopaye day",
    timezone: "Clock para “bello day”",
    tracking: "Wat me count?",
    submit: "Papoy board",
  },
  score: {
    minutes: "Tick",
    seconds: "Tock",
    secondMark: " po",
    lowerWins: "Small time win. Save swap da kaboom score.",
    replacesFinale: "Save swap da kaboom score.",
    replacesDay: "Dis swap da day total{unit}.",
    save: "Tank yu",
  },
  invite: {
    preparing: "Banana link…",
    label: "Bello link",
    copied: "Sa la ka",
    copy: "Me copy",
  },
  templates: {
    pushups: {
      name: "Pushy moon",
      blurb: "Pushy every day. Last bit, one big pushy. Kaboom.",
    },
    grind: {
      name: "Da big grind",
      blurb: "Pushy, pully, miles, then one big pushy.",
    },
    presidential: {
      name: "Boss test",
      blurb: "Pushy every day, then da test: pushy, sitty, pully, and one mile.",
    },
  },
  tz: {
    pacific: "Pacific, bello",
    mountain: "Mountain, bello",
    arizona: "Arizona, bello",
    central: "Central, bello",
    eastern: "Eastern, bello",
    hawaii: "Hawaii, bello",
    london: "London, bello",
    europe: "Europe, bello",
    india: "India, bello",
    tokyo: "Tokyo, bello",
    sydney: "Sydney, bello",
    utc: "UTC, bello",
  },
  err: {
    check: "Luk again. Bi-do.",
    negative: "No no no minus number.",
    tooBig: "Number too banana big.",
    time: "Tick tock under one day.",
    nameShort: "Board need name. Bello.",
    nameLong: "Name too long. Bi-do 60.",
    start: "Pick da go day.",
    end: "Pick da poopaye day.",
    zone: "Pick da clock from da list.",
    endBefore: "Poopaye day come after go day.",
    span: "Board only 45 banana days.",
    notOnBoard: "Me no on dis board. Bi-do.",
    logMissing: "Log go bi-do.",
    dayOutside: "Day no on da board.",
    future: "No no no future day.",
    eventMissing: "Kaboom go bi-do.",
    finaleClosed: "Kaboom window poopaye.",
    renameLength: "Name 2 to 60. Pwede na.",
    renameOwner: "Only boss swap da name.",
    nickLength: "Nickname too long. Bi-do 24.",
    trackerName: "Name da count. Bello.",
    trackerNameLong: "Count name too long. Bi-do 40.",
    unitLong: "Bits name too long. Bi-do 12.",
    ownerOnly: "Only boss papoy tracker.",
  },
  ok: {
    saved: "Tank yu.",
    finaleSaved: "Kaboom score tank yu.",
    nameUpdated: "Name swap. Sa la ka.",
    nicknameSaved: "Nickname tank yu.",
    accountName: "Me use account name.",
    trackerAdded: "{name} po ka board.",
  },
} satisfies Copy;

export function fill(template: string, values: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => {
    const value = values[key];
    return value === undefined ? match : String(value);
  });
}
